package com.gdavidpb.tuindice.record.domain.model

enum class SyntheticTermLoadDetail {
	PERSONAL_HISTORY_STRONG,
	PERSONAL_HISTORY_LIMITED,
	CAREER_REFERENCE,
	GLOBAL_REFERENCE,
	UNKNOWN_SUBJECT,
	MISSING_SUBJECT_DIFFICULTY,
	INSUFFICIENT_REFERENCE_DATA
}
